data Cardiology;
infile 'Cardiology.txt' delimiter = '09'x firstobs = 2 missover;
input age	sex	chest_pain_type	blood_pressure	cholesterol	Fasting_blood_sugar	resting_ecg	maximum_heart_rate	angina	heart_condition;
dum_cpt1 = (chest_pain_type = 1);
dum_cpt2 = (chest_pain_type = 2);
dum_cpt3 = (chest_pain_type = 3);
dum_r_ecg1 = (resting_ecg = 1);
dum_r_ecg2 = (resting_ecg = 2);
run;
proc print;
run;
Title "Frequency of Heart Condition";
Proc Freq data = cardiology;
table heart_condition;
run;
PROC SORT; 
BY heart_condition;
RUN;
Proc Boxplot; 
Plot age * heart_condition;
RUN;
Proc Boxplot; 
Plot maximum_heart_rate * heart_condition;
RUN;
Title 'Test and train set for Heart Condition';
Proc surveyselect data = cardiology out = train seed = 592587 samprate = 0.8 outall;
run;
proc print data = train;
run;
proc freq data = train;
tables selected;
run;
data train;
set train;
if selected then new_y = Heart_condition;
run;
proc logistic data = train;
model new_y  (event = '1')= age	sex	dum_cpt1 dum_cpt2 dum_cpt3 	blood_pressure	cholesterol	Fasting_blood_sugar	dum_r_ecg1 dum_r_ecg2	maximum_heart_rate	angina /  stb;
run;
proc logistic data = train;
model new_y  (event = '1')= age	sex	dum_cpt1 dum_cpt2 dum_cpt3 	blood_pressure	cholesterol	Fasting_blood_sugar	dum_r_ecg1 dum_r_ecg2	maximum_heart_rate	angina / selection = stepwise rsquare stb;
run;
proc logistic data = train;
model new_y  (event = '1')= age	sex	dum_cpt1 dum_cpt2 dum_cpt3 	blood_pressure	cholesterol	Fasting_blood_sugar	dum_r_ecg1 dum_r_ecg2	maximum_heart_rate	angina / selection = forward rsquare stb;
run;
proc logistic data = train;
model new_y  (event = '1')= age	sex	dum_cpt1 dum_cpt2 dum_cpt3 	blood_pressure	cholesterol	Fasting_blood_sugar	dum_r_ecg1 dum_r_ecg2	maximum_heart_rate	angina / selection = backward rsquare stb;
run;
Title "Check of Collinearity, Outliers and Influencers";
proc logistic data = train;
model new_y  (event = '1')= sex	dum_cpt1 dum_cpt2 dum_cpt3 	maximum_heart_rate / influence iplots corrb stb;
run;
data train_02;
SET train;
IF _N_ IN (124,134,215,258) THEN DELETE;
RUN;
proc logistic data = train_02;
model new_y  (event = '1')= 	sex	dum_cpt1 dum_cpt2 dum_cpt3 	maximum_heart_rate / rsquare influence iplots corrb stb;
run;
data train_03;
SET train_02;
IF _N_ IN (126,254) THEN DELETE;
RUN;
proc logistic data = train_03;
model new_y  (event = '1')= sex	dum_cpt1 dum_cpt2 dum_cpt3 	maximum_heart_rate /  rsquare influence iplots corrb stb;
run;
*deleting influential points;
data train_04;
SET train_03;
IF _N_ IN (4,5,8,9,12,17,18,23,29,31,38,42,48,52,55,57,59,74,86,87,88,91,99,105,110,121,125,129,137,138,139,144,149,154,155,166,174,183,188,189,191,196,207,217,230,237,238,251,251,254,258,262,276,293,295) THEN DELETE;
RUN;
proc logistic data = train_04;
model new_y  (event = '1')= sex	dum_cpt1 dum_cpt2 dum_cpt3 	maximum_heart_rate /  rsquare influence iplots corrb stb;
run;
data train_05;
SET train_04;
IF _N_ IN (28,83,99,214) THEN DELETE;
RUN;
proc logistic data = train_05;
model new_y  (event = '1')= sex	dum_cpt1 dum_cpt2 dum_cpt3 	maximum_heart_rate /  rsquare influence iplots corrb stb;
run;
Title "Final Model" ;
proc logistic data = train_03;
model new_y  (event = '1')= sex	dum_cpt1 dum_cpt2 dum_cpt3 	maximum_heart_rate / rsquare stb;
run;
Title "Predictions";
data new ; 
input age	sex	chest_pain_type 	blood_pressure	cholesterol	Fasting_blood_sugar	 resting_ecg	maximum_heart_rate	angina;
datalines;
62	1	4	128	210	0	2	130	1	
54	1	2	135	260	0	0	168	0	
;
data pred; 
set new train_03;
dum_cpt1 = (chest_pain_type = 1);
dum_cpt2 = (chest_pain_type = 2);
dum_cpt3 = (chest_pain_type = 3);
dum_r_ecg1 = (resting_ecg = 1);
dum_r_ecg2 = (resting_ecg = 2);
run;
proc logistic;
model new_y  (event = '1')= 	sex	dum_cpt1 dum_cpt2 dum_cpt3 	maximum_heart_rate;
output out = pred p = phat lower = lcl  upper = ucl predprobs = (individual);
run;
proc print data = pred; 
Title " Predicted Probabilities";
run;
proc freq data = train_03;
tables new_y;
run;
Title 'Validation Test Set ';
proc logistic data = train_03;
model new_y  (event = '1')= 	sex	dum_cpt1 dum_cpt2 dum_cpt3 maximum_heart_rate /ctable pprob = (0.2 to 0.8 by 0.05)	 ;
output out = pred_01 (where = (new_y = .)) p = phat lower = lcl  upper = ucl predprobs = (individual);
run;
data probs;
set pred_01;
pred_dis = 0;
threshold = 0.4;
if phat>threshold then pred_dis = 1;
run;
proc freq data= probs;
tables heart_condition*pred_dis / norow nocol nopercent;
run;
